import type { infer as zInfer } from "zod";
import { array, object, strictObject, string, unknown, uuid, enum as zEnum, number as zNumber } from "zod";

// `.meta({ id })` names a schema as a reusable component in the OpenAPI spec;
// `description` and `examples` show up in the docs and seed Swagger's "Try it out".
// None of it changes how a schema validates.

export const Category = {
  Arrows: "Arrows",
  Masks: "Masks",
  Potions: "Potions",
  Shields: "Shields"
} as const;
export const CategorySchema = zEnum(Category).meta({ id: "Category" });
export type Category = (typeof Category)[keyof typeof Category];

export const ProductId = uuid().meta({
  description: "Generated by the API when the product is created.",
  examples: ["7f3b9d1e-2c4a-4f6b-8d5e-1a2b3c4d5e6f"]
});

export const Product = strictObject({
  id: ProductId,
  title: string()
    .min(1)
    .max(200)
    .meta({ examples: ["Potion of Mild Inconvenience"] }),
  description: string()
    .nonempty()
    .meta({ examples: ["Restores 1 HP. Tastes of pennies."] }),
  price: zNumber()
    .int()
    .positive()
    .meta({ examples: [25] }),
  category: CategorySchema
}).meta({ id: "Product" });
export type Product = zInfer<typeof Product>;

export const ProductList = array(Product);

export const ProductCreateData = Product.omit({ id: true }).meta({ id: "ProductCreateData" });
export type ProductCreateData = zInfer<typeof ProductCreateData>;

export const ProductUpdateData = Product.omit({ id: true, category: true }).meta({ id: "ProductUpdateData" });
export type ProductUpdateData = zInfer<typeof ProductUpdateData>;

/** The body withErrorHandling sends for every error response. */
export const ErrorResponse = object({
  message: string().meta({ examples: ["Product with ID 7f3b9d1e-2c4a-4f6b-8d5e-1a2b3c4d5e6f does not exist."] }),
  details: unknown()
    .optional()
    .meta({ description: "Field-level validation errors. Present only when the request failed validation." })
}).meta({ id: "ErrorResponse" });
