import type { infer as zInfer } from "zod";
import { array, object, strictObject, string, unknown, url, uuid, enum as zEnum, number as zNumber } from "zod";

export const Category = {
  Arrows: "Arrows",
  Masks: "Masks",
  Potions: "Potions",
  Shields: "Shields"
} as const;
export const CategorySchema = zEnum(Category).meta({ id: "Category" });
export type Category = (typeof Category)[keyof typeof Category];

export const ProductId = uuid().meta({
  description: "Generated by the API when the product is created.",
  examples: ["7f3b9d1e-2c4a-4f6b-8d5e-1a2b3c4d5e6f"]
});

export const Product = strictObject({
  id: ProductId,
  title: string()
    .min(1)
    .max(200)
    .meta({ examples: ["Potion of Mild Inconvenience"] }),
  description: string()
    .nonempty()
    .meta({ examples: ["Restores 1 HP. Tastes of pennies."] }),
  price: zNumber()
    .int()
    .positive()
    .meta({ examples: [25] }),
  category: CategorySchema,
  images: url().array().optional().meta({ description: "List of presigned download URLs for images for this product." })
}).meta({ id: "Product" });
export type Product = zInfer<typeof Product>;

export const ProductList = array(Product);

export const ProductCreateData = Product.omit({ id: true, images: true }).meta({ id: "ProductCreateData" });
export type ProductCreateData = zInfer<typeof ProductCreateData>;

export const ProductUpdateData = Product.omit({ id: true, category: true, images: true }).meta({
  id: "ProductUpdateData"
});
export type ProductUpdateData = zInfer<typeof ProductUpdateData>;

export const ImageContentType = zEnum(["image/gif", "image/jpeg", "image/png", "image/webp"]).meta({
  id: "ImageContentType",
  description: "The MIME type the browser must send as the Content-Type header when PUTting to the presigned URL."
});
export type ImageContentType = zInfer<typeof ImageContentType>;

export const UploadProductImageData = strictObject({
  contentType: ImageContentType,
  filename: string()
    .min(1)
    .max(50)
    .regex(/^[a-zA-Z0-9- _]+(\.[a-zA-Z0-9]+)*$/, {
      message:
        "File names may only container letters, numbers, dashes, hyphens, or spaces and may optionally end with a file type specifier."
    })
    .meta({
      description: "The name of the file to upload, optionally with a type specifier at the end.",
      example: "Wooden Shield.jpg"
    })
}).meta({ id: "UploadProductImageData" });
export type UploadProductImageData = zInfer<typeof UploadProductImageData>;

export const UploadProductImageResponse = strictObject({
  url: url()
});
export type UploadProductImageResponse = zInfer<typeof UploadProductImageResponse>;

export const ErrorResponse = object({
  message: string().meta({ examples: ["Product with ID 7f3b9d1e-2c4a-4f6b-8d5e-1a2b3c4d5e6f does not exist."] }),
  details: unknown()
    .optional()
    .meta({ description: "Field-level validation errors. Present only when the request failed validation." })
}).meta({ id: "ErrorResponse" });
